dist: xenial   # required for Python >= 3.7
language: python
python: "3.7"
before_install:
  - pip install poetry
install:
  # we run `poetry version` here to appease poetry about '0.0.0-source'
  - poetry version
  - poetry install
script:
 - poetry run python --version
 - poetry run behave
before_deploy:
  - pip install poetry
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
  - poetry version $TRAVIS_TAG
  - make build
deploy:
  provider: script
  script: make release
  skip_cleanup: true
  draft: true
  on:
    branch: master
    tags: true
